project:
  type: book
  output-dir: quarto

book:
  title: "Quarto Template"
  author: "Ivan Jacob Agaloos Pesigan"
  date: today
  search: true
  repo-url: https://github.com/ijapesigan/dynamicalSystemsNotes
  repo-actions: [edit]
  site-url: https://ijapesigan.github.io/dynamicalSystemsNotes/index.html
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - qmd/intro/intro.qmd
    - qmd/references/references.qmd
  appendices:
    - qmd/session/session.qmd
bibliography: qmd/bib/bib.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

format:
  html:
    theme:
      - flatly
      - scss/custom.scss
    number-sections: false
